### ISSUE TITLE
enable travis-ci

### ISSUE THREAD

**Issue by xuwei-k** [scalatra/scalatra-sbt.g8#42]

**Comment by seratch** [comment]
ping @rossabaker 
I don't have a permission to enable Travis builds. https://travis-ci.org/profile/scalatra

**Comment by xuwei-k** [comment]
ping @rossabaker @casualjim

**Comment by rossabaker** [comment]
I'm sorry.  I fell behind on GitHub notifications around that time and hadn't seen this.  I just enabled it.

@seratch should have full rights on the org.  If not, let me know, and I'll figure out why not.

**Comment by seratch** [comment]
@rossabaker Thanks. I found I've got admin permission now.

**Comment by mufl1c** [comment]
ping

2015-07-15 8:35 GMT+07:00 kenji yoshida <notifications@github.com>:

**Comment by seratch** [comment]
Already enabled. https://travis-ci.org/scalatra/scalatra-sbt.g8/pull_requests
