### ISSUE TITLE
aux-compile task is missing

### ISSUE THREAD

**Issue by t3chnoboy** [scalatra/scalatra-sbt.g8#46]
Hi!
I'm trying to go through the tutorial http://www.scalatra.org/getting-started/first-project.html
And when I run:
```
> container:start
> ~ ;copy-resources;aux-compile
 ```
I'm getting the following error: `[error] Not a valid command: aux-compile`
Any ideas? Auto reload would be very helpful.
I've been also trying https://github.com/spray/sbt-revolver without any luck :disappointed:

**Comment by rossabaker** [comment]
That looks like doc bitrot.  `aux-compile` went away with xsbt-web-plugin 1.0.  It has been [simplified by the plugin](https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/1.0.md#triggered-relaunch):

> `~container:start`
> This starts the container, then monitors the sources, resources, and webapp directories for changes, which triggers a container restart.

**Comment by t3chnoboy** [comment]
It works! Thank you!

**Comment by t3chnoboy** [comment]
https://github.com/scalatra/scalatra-website/pull/100
