### ISSUE TITLE
support Scala 2.12

### ISSUE THREAD

**Issue by xuwei-k** [scalatra/scalatra-sbt.g8#57]
```
[info] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[info] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] [warn] 	:: com.mojolly.scalate#scalate-generator_2.12;0.5.0: not found
[info] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[info] [warn] 
[info] [warn] 	Note: Unresolved dependencies path:
[info] [warn] 		com.mojolly.scalate:scalate-generator_2.12:0.5.0 ((com.mojolly.scalate.ScalatePlugin) ScalatePlugin.scala#L110)
[info] [warn] 		  +- com.example:my-scalatra-web-app_2.12:0.1.0-SNAPSHOT
[info] sbt.ResolveException: unresolved dependency: com.mojolly.scalate#scalate-generator_2.12;0.5.0: not found
```

https://github.com/scalatra/scalatra-sbt.g8/blob/1e91076652c084e42f75c3fa762cc45123291a26/src/main/g8/project/plugins.sbt#L3

drop scalate-generator dependency from scalatra-sbt.g8 ?

or

release `scalate-generator_2.12` ? ( https://github.com/scalate/xsbt-scalate-generate ?)

**Comment by hardlianotion** [comment]
Looks like [this](https://github.com/skinny-framework/sbt-scalate-precompiler) is a drop-in, maintained version of xsbt-scalate-generate (discovered this browing the xsbt-scalate-generate project).  It works with scala 2.12.
